# Generated by Django 4.2.10 on 2024-02-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewBody', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewBook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewBook', to='dojoReadsAPP.book')),
                ('reviewCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewUser', to='dojoReadsAPP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentBody', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commentCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentUser', to='dojoReadsAPP.user')),
                ('commentReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReview', to='dojoReadsAPP.review')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bookCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookUser', to='dojoReadsAPP.user'),
        ),
    ]
