# Generated by Django 5.0.2 on 2024-02-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoReadsAPP', '0002_auto_20210505_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='reviewBody',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewBook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewBook', to='dojoReadsAPP.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookUser', to='dojoReadsAPP.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewUser', to='dojoReadsAPP.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentBody', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commentCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentUser', to='dojoReadsAPP.user')),
                ('commentReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReview', to='dojoReadsAPP.review')),
            ],
        ),
    ]
